# Syncer Configuration.

log-level = "info"
log-file = "syncer.log"
log-rotate = "day"

server-id = 101

meta = "./syncer.meta"
worker-count = 16
batch = 1000
flavor = "mysql"

status-addr = ":10081"

# max-retry is used for retry when network interruption.
max-retry = 100

# Notice: skip-sqls is abandoned, please use skip-ddls instead.
# skip-ddls skip ddl statements which supports regular expression. When there are DDL sqls incompatible with tidb, you should skip them via these rules.
# skip-ddls = ["^CREATE\\s+USER"]

# Notice: skip-events is abandoned, please use skip-dmls instead
# skip-dmls skip DML statements. type value can be 'insert', 'update', 'delete'.
# skip delete statements in foo.bar table.
# [[skip-dmls]]
# db-name = "foo"
# tbl-name = "bar"
# type = "delete"
# 
# skip all delete statements.
# [[skip-dmls]]
# type = "delete"
# 
# skip all delete statements in all foo.* tables.
# [[skip-dmls]]
# db-name = "foo"
# type = "delete"


## do-db has priority over do-table if have same db name
## and we support regular expression , start with '~' declare use regular expression.
#
#do-db = ["~^b.*","s1"]
#[[do-table]]
#db-name = "test"
#tbl-name = "log"

#[[do-table]]
#db-name = "test"
#tbl-name = "~^a.*"

## ignore-db has priority over ignore-table if have same db name
## and we support regular expression , start with '~' declare use regular expression.
#
#ignore-db = ["~^b.*","s1"]
#[[ignore-table]]
#db-name = "your_db"
#tbl-name = "your_table"

#[[ignore-table]]
#db-name ="test"
#tbl-name = "~^a.*"

# our Selector is a two level selector (schemal level, and table level)
# in order to support `renameShardingSchema`, always need this extra rule
# [[route-rules]]
# schema-pattern = "route_*"
# target-schema = "route"

#[[route-rules]]
#schema-pattern = "route_*"
#table-pattern = "abc_*"
#target-schema = "route"
#target-table = "abc"

#[[route-rules]]
#schema-pattern = "route_*"
#table-pattern = "xyz_*"
#target-schema = "route"
#target-table = "xyz"


[from]
host = "127.0.0.1"
user = "root"
password = ""
port = 3306

[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 4000
