# Master Configuration.

log-level = "info"
log-file = "dm-master.log"
log-rotate = "day"

master-addr = ":8261"

# mysql <-> Worker deployment, we'll refine it when new deployment function is available

[[deploy]]
source-id = "mysql-replica-01"
dm-worker = "172.16.10.72:8262"

[[deploy]]
source-id = "mysql-replica-02"
dm-worker = "172.16.10.73:8262"
