# Master Configuration.

log-level = "info"
log-file = "dm-master.log"
log-rotate = "day"

master-addr = ":11080"
status-addr = ":11081"

# mysql <-> Worker deployment, we'll refine it when new deployment function is available

[[deploy]]
source-id = "mysql-replica-01"
dm-worker = "172.16.10.72:10081"

[[deploy]]
source-id = "mysql-replica-02"
dm-worker = "172.16.10.73:10081"
