# Worker Configuration.

log-level = "info"
log-file = "dm-worker.log"
log-rotate = "day"

worker-addr = ":10081"
status-addr = ":10082"


server-id = 101
source-id = "127.0.0.1:3306"
flavor = "mysql"
relay-dir = "./relay_log"
meta-file = "relay.meta"
enable-gtid = false
# charset= ""

[from]
host = "127.0.0.1"
user = "root"
password = ""
port = 3306
