# Base Configuration.

# sub task name as identifier, should be unique
name = "sub-task-name"

# sub task mode, can be `all`, `full`, `increment`
mode = "all"

# used for binlog replication
server-id = 101


# Mydumper configuration

# mydumper binary path
mydumper-path = "./mydumper"

# -t, --threads
#threads = 16

# -F, --chunk-filesize
#chunk-filesize = 64

# --skip-tz-utc
#skip-tz-utc = true

# other extra args
#extra-args = "-B test -T t1,t2 --no-locks"


# Loader configuration

# Number of threads restoring concurrently for loader worker pool. Each worker restore one file at a time, increase this as TiKV nodes increase
pool-size = 16

# Directory of the dump to import
dir = "./"

# We saved checkpoint data to tidb, which schema name is defined here.
checkpoint-schema = "tidb_loader"

# An alternative database to restore into
alternative-db = ""

# Database to restore
source-db = ""


# Syncer configuration

# different sub task should have different meta
meta = "./syncer.subTaskA.meta"

worker-count = 16
batch = 1000
flavor = "mysql"

# max-retry is used for retry when network interruption.
max-retry = 100


# Notice: skip-sqls is abandoned, please use skip-ddls instead.
# skip-ddls skip ddl statements which supports regular expression. When there are DDL sqls incompatible with tidb, you should skip them via these rules.
# skip-ddls = ["^CREATE\\s+USER"]

# Notice: skip-events is abandoned, please use skip-dmls instead
# skip-dmls skip DML statements. type value can be 'insert', 'update', 'delete'.
# skip delete statements in foo.bar table.
# [[skip-dmls]]
# db-name = "foo"
# tbl-name = "bar"
# type = "delete"
#
# skip all delete statements.
# [[skip-dmls]]
# type = "delete"
#
# skip all delete statements in all foo.* tables.
# [[skip-dmls]]
# db-name = "foo"
# type = "delete"


# our Selector is a two level selector (schemal level, and table level)
# in order to support `renameShardingSchema`, always need this extra rule
# [[route-rules]]
# schema-pattern = "shard_db_*"
# target-schema = "shard_db"

# [[route-rules]]
# schema-pattern = "shard_db_*"
# table-pattern = "shard_table_*"
# target-schema = "shard_db"
# target-table = "shard_table"


#do-db = ["~^b.*","s1"]
#[[do-table]]
#db-name ="test"
#tbl-name = "log"


#ignore-db = ["~^c.*","s2"]
#[[ignore-table]]
#db-name ="test"
#tbl-name = "~^a.*"


# to: the target db
# from: the source db, not in this file, auto get it from worker's config
[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 4000
